name: My CI/CD Workflow

on:
  push:
    branches: 
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
                echo "Building code."

      - name: Deploying
        run: |
                echo "Deploying code."
