name: My CI/CD Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
                echo "Building code."

      - name: Testing
        run: |
                echo "Testing code"

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checking
        run: |
            echo "${pwd}"
            pwd
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: get branch name
        run: |
            echo branch name ${GITHUB_REF##*/}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
