name: My CI/CD Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
                echo "Building code."

      - name: Testing
        run: |
                echo "Testing code"

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checking
        run: |
            echo "${pwd}"
            pwd
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: ./docs/*
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
