name: My CI/CD Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
                echo "Building code."

      - name: Testing
        run: |
                echo "Testing code"

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checking
        run: |
            echo "${pwd}"
            pwd
      - name: get branch name
        run: |
            echo branch name ${GITHUB_REF##*/}

      
      

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            path: './docs/index.html'
      - name: Deploy to GH Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
           github_token: ${{secrets.GITHUB_TOKEN}}
           publish_dir: ./docs
